package xcompose

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"

	"keyboard/pkg/config"
)

func GenerateFile(configPath string, outputPath string) error {
	cfg, err := config.LoadRuntime(configPath)
	if err != nil {
		return err
	}

	symbols, err := collectMappedSymbols(cfg)
	if err != nil {
		return err
	}

	content, err := BuildContent(symbols)
	if err != nil {
		return err
	}

	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create output dir %s: %w", dir, err)
		}
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	return nil
}

func collectMappedSymbols(cfg config.Runtime) ([]rune, error) {
	set := make(map[rune]struct{})
	addMap := func(mappings map[uint16]config.CompiledMapping) error {
		for _, mapping := range mappings {
			if mapping.Kind != config.MappingSymbol {
				continue
			}
			if mapping.Symbol == 0 {
				return errors.New("symbol mapping has empty symbol")
			}
			set[mapping.Symbol] = struct{}{}
		}
		return nil
	}

	if err := addMap(cfg.AltMappings); err != nil {
		return nil, err
	}
	if err := addMap(cfg.CapsMappings); err != nil {
		return nil, err
	}
	for _, mapping := range cfg.ComboMappings {
		if mapping.Kind != config.MappingSymbol {
			continue
		}
		if mapping.Symbol == 0 {
			return nil, errors.New("symbol mapping has empty symbol")
		}
		set[mapping.Symbol] = struct{}{}
	}

	symbols := make([]rune, 0, len(set))
	for r := range set {
		symbols = append(symbols, r)
	}
	sort.Slice(symbols, func(i, j int) bool { return symbols[i] < symbols[j] })
	return symbols, nil
}

func BuildContent(symbols []rune) (string, error) {
	var b strings.Builder
	b.WriteString("# Auto-generated by kmap generate-xcompose\n")
	b.WriteString("# Sequence format: <Multi_key> <length> <decimal unicode codepoint>\n")

	for _, symbol := range symbols {
		entry, err := EntryForRune(symbol)
		if err != nil {
			return "", err
		}
		b.WriteString(entry)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func EntryForRune(symbol rune) (string, error) {
	if symbol == utf8.RuneError || !utf8.ValidRune(symbol) {
		return "", fmt.Errorf("invalid symbol rune: %U", symbol)
	}

	decimal := strconv.Itoa(int(symbol))
	hex := fmt.Sprintf("%04X", symbol)
	length := strconv.Itoa(len(decimal))

	var b strings.Builder
	b.WriteString("<Multi_key> <")
	b.WriteString(length)
	b.WriteString(">")
	for _, digit := range decimal {
		b.WriteString(" <")
		b.WriteRune(digit)
		b.WriteString(">")
	}
	b.WriteString(" : \"")
	b.WriteString(escapeSymbol(symbol))
	b.WriteString("\" U")
	b.WriteString(hex)
	return b.String(), nil
}

func escapeSymbol(symbol rune) string {
	switch symbol {
	case '\\':
		return "\\\\"
	case '"':
		return "\\\""
	case '\n':
		return "\\n"
	case '\t':
		return "\\t"
	default:
		return string(symbol)
	}
}
